services:
  - type: web
    name: plant-disease-backend
    env: python
    plan: free
    runtime: python-3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn inference_api:app
